# {{projectName}}

{{description}}

Golden-path scaffold generated by the IDP scaffolder from the `ANGULAR`
template. Owned by **{{ownerTeam}}**.

## Stack

- Angular 17 standalone components + Signals, TypeScript 5
- Quality gate: ESLint (`npm run lint`)
- Runtime: multi-stage Dockerfile over nginx
- CI/CD: `.github/workflows/deploy.yml` (lint -> build -> image -> deploy)

## Local run

```bash
cp .env.example .env
npm ci && npm start
```

Build with `npm run build` (strict TypeScript + ESLint gate in `npm run lint`).