# {{projectName}}

{{description}}

Golden-path scaffold generated by the IDP scaffolder from the `PYTHON`
template. Owned by **{{ownerTeam}}**.

## Stack

- Python 3.12 / FastAPI, async SQLAlchemy-ready layout
- Quality gate: Ruff (`ruff check .`) + pytest
- Runtime: multi-stage Dockerfile (uvicorn runtime)
- CI/CD: `.github/workflows/deploy.yml` (lint -> test -> build -> image -> deploy)

## Local run

```bash
cp .env.example .env
python -m venv .venv && .venv/bin/pip install -e ".[dev]"
.venv/bin/uvicorn src.{{packageName}}.main:app --port 8000
```

Health: `GET /health` — Repository: https://github.com/{{repoName}}