# {{projectName}}

{{description}}

Golden-path scaffold generated by the IDP scaffolder from the `SPRING_BOOT`
template. Owned by **{{ownerTeam}}**.

## Stack

- Java 17 / Spring Boot 3.2 (Maven build)
- Quality gate: Checkstyle (`./mvnw checkstyle:check`)
- Runtime: multi-stage Dockerfile with distroless-style JRE image
- CI/CD: `.github/workflows/deploy.yml` (lint -> test -> build -> image -> deploy)

## Local run

```bash
cp .env.example .env
./mvnw spring-boot:run
```

Health: `GET /actuator/health` — Repository: https://github.com/{{repoName}}