# {{projectName}}

{{description}}

Golden-path scaffold generated by the IDP scaffolder from the `GO` template.
Owned by **{{ownerTeam}}**.

## Stack

- Go 1.22, standard library `net/http` (Gin-ready layout)
- Quality gate: golangci-lint (`golangci-lint run`)
- Runtime: multi-stage Dockerfile (distroless runtime)
- CI/CD: `.github/workflows/deploy.yml` (lint -> test -> build -> image -> deploy)

## Local run

```bash
cp .env.example .env
go run ./cmd/api
```

Health: `GET /health` — Repository: https://github.com/{{repoName}}